spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka

logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: info

server:
  port: 8080
