spring:
  application:
    name: message-service

  data:
    redis:
      host: redis
      port: 6379
      timeout: 100000

  kafka:
    bootstrap-servers: kafka1:9092, kafka2:9093, kafka3:9094
    listener:
      ack-mode: record
    consumer:
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: jeXWnV9fY7BPLPEuJaBnJVETR1M5pSpXtDmnqy1KK1py+gLvFCMe1u84F8t5ZkNH
  lifetime: 60000

kafka:
  topic:
    db:
      save: db-save-topic
      transaction-id: db-save-topic-transaction-id
    s3:
      save: s3-save-topic
      transaction-id: s3-topic-transaction-id

grpc:
  client:
    user-grpc-service:
      address: 'discovery:///user-database-service'
      negotiation-type: plaintext
    message-address-db-grpc-service:
      address: 'discovery:///message-address-db-service'
      negotiation-type: plaintext
    message-s3-grpc-service:
      address: 'discovery:///message-s3-service'
      negotiation-type: plaintext


server:
  port: 0
