spring:
  application:
    name: message-service

  data:
    redis:
      host: redis
      port: 6379
      timeout: 100000

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka
    register-with-eureka: true
    fetch-registry: false

jwt:
  secret: jeXWnV9fY7BPLPEuJaBnJVETR1M5pSpXtDmnqy1KK1py+gLvFCMe1u84F8t5ZkNH
  lifetime: 600000

server:
  port: 0
