version: '3.7'

services:
  service-discovery:
    container_name: service-discovery
    build: /service-discovery/.
    ports:
      - "8761:8761"

  api-gateway:
    container_name: api-gateway
    build: /api-gateway/.
    depends_on:
      - service-discovery