version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=1
    restart: always

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=userpassword
    command: server ~/minio --console-address :9090
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - D:\minio_datapart:/var/lib/minio/data
    restart: always

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: social_web
      POSTGRES_USER: bestuser
      POSTGRES_PASSWORD: bestuser
    volumes:
      - D:\postgres_datapart:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always