version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: social_web
      POSTGRES_USER: bestuser
      POSTGRES_PASSWORD: bestuser
    volumes:
      - D:\postgres_datapart:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  service-discovery:
    container_name: service-discovery
    build: /service-discovery/.
    restart: always
    ports:
      - "8761:8761"

  api-gateway:
    container_name: api-gateway
    build: /api-gateway/.
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - service-discovery

  authentication-service:
    container_name: authentication-service
    build: /authentication-service/.
    restart: always
    depends_on:
      - postgres
      - api-gateway
      - redis

  user-database-service:
    container_name: user-database-service
    build: /user-database-service/.
    restart: always
    depends_on:
      - authentication-service

  friendship-service:
    container_name: friendship-service
    build: /friendship-service/.
    restart: always
    depends_on:
      - authentication-service

  message-service:
    container_name: message-service
    build: /message-service/.
    restart: always
    depends_on:
      - message-address-db-service
      - message-s3-service

  message-address-db-service:
    container_name: message-address-db-service
    build: /message-address-db-service/.
    restart: always
    depends_on:
      - authentication-service
      - kafka1
      - kafka2
      - kafka3

  message-s3-service:
    container_name: message-s3-service
    build: /message-s3-service/.
    restart: always
    depends_on:
      - authentication-service
      - kafka1
      - kafka2
      - kafka3

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=1
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    restart: always

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=userpassword
    command: server ~/minio --console-address :9090
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - D:\minio_datapart:/var/lib/minio/data
    restart: always

  kafka1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      restart: always

  kafka2:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka1
    ports:
      - "29093:29093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093,PLAINTEXT_HOST://localhost:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      restart: always

  kafka3:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka2
    ports:
      - "29094:29094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094,PLAINTEXT_HOST://localhost:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    restart: always
