spring:
  application:
    name: message-s3-service

  kafka:
    bootstrap-servers: kafka1:9092, kafka2:9092, kafka3:9092
    listener:
      ack-mode: record
    consumer:
      auto-offset-reset: earliest
      group-id: s3-save-request

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka
    register-with-eureka: true
    fetch-registry: true

minio:
  url: http://minio:900
  bucket: messages
  security:
    access-key: user
    secret-key: userpassword

kafka:
  topic:
    s3:
      save: s3-save-topic

server:
  port: 0
